app: jetbrains
-
add imports: key(alt-shift-enter)
app debug: user.idea("action Debug")
app run: user.idea("action Run")
app stop: key(ctrl-f2)
collapse: key(ctrl--)
expand: key(ctrl-=)
(search | find): user.idea("action FindInPath")
(search | find) action: user.idea("action GotoAction")
replace: user.idea("action ReplaceInPath")
replace it: user.idea("action Replace")
format: user.idea("action ReformatCode")
git add: user.idea("action ChangesView.AddUnversioned")
git copy: key(ctrl-shift-g)
git branch: user.idea("action Git.Branches")
git branch new: key(ctrl-alt-n)
go next: key(alt-shift-down)
go last: key(alt-shift-up)
jump source: key(f4)
project last: key(ctrl-alt-[)
project next: key(ctrl-alt-])
rollback: key(ctrl-alt-z)
patch create: user.idea("action ChangesView.CreatePatch")
patch apply: user.idea("action ChangesView.ApplyPatch")
(delete | remove) line: user.idea("action EditorDeleteLine")
line move down: user.idea("action MoveLineDown")
line move up: user.idea("action MoveLineUp")
settings: user.idea("action ShowSettings")
refresh: user.idea("action Synchronize")
target: 
    key(alt-shift-1) 
    key(1)
toggle claude: key(ctrl-escape)
toggle chat: key(alt-shift-4)
toggle request: key(alt-0)

# Override
comment: key(ctrl-/)
copy path: key(ctrl-alt-shift-c)